### PR TITLE
Make the caching feature enabled by default.

### PR DESCRIPTION
**Pull request by ttkzw**
This pull request makes the caching feature enabled by default.
To disable the caching feature, you can set `--cachetime=0`.

### CODE REVIEW

**Comment by netmarkjp** [comment]
Thanks.
`--cache` option remaining but no effect, I think this behavior is confusing.

Which is better? or any other ideas?

- when `--cache` passed, automatically set `0` to `--cachetime`. and show deprecate warning to stderr
- when `--cache` passed, return error (no backward compatibility)
- remove `--cache` option (no backward compatibility)

**Comment by ttkzw** [comment]
I think we can delete the `--cache` option,
because it is not so long since implementing the cache feature,

**Comment by netmarkjp** [comment]
I think so too. Remove `--cache` is good.

**Comment by ttkzw** [comment]
I will remove `--cache` option soon.

**Comment by ttkzw** [comment]
> I will remove `--cache` option soon.

Done.

**Comment by netmarkjp** [comment]
Thanks!

**Pull request merged**
